name: 'GrabShot - Website Screenshot'
description: 'Capture beautiful website screenshots in CI/CD. Device frames, full-page, AI cleanup.'
author: 'GrabShot'
branding:
  icon: 'camera'
  color: 'blue'
inputs:
  url:
    description: 'URL to screenshot'
    required: true
  api-key:
    description: 'GrabShot API key (free at grabshot.dev)'
    required: true
  width:
    description: 'Viewport width'
    default: '1280'
  height:
    description: 'Viewport height'
    default: '720'
  full-page:
    description: 'Capture full page'
    default: 'false'
  device-frame:
    description: 'Device frame (none/macbook/iphone/ipad/pixel)'
    default: 'none'
  format:
    description: 'Output format (png/jpeg/webp)'
    default: 'png'
  output:
    description: 'Output file path'
    default: 'screenshot.png'
  delay:
    description: 'Wait before capture (ms)'
    default: '0'
outputs:
  file:
    description: 'Path to the screenshot file'
runs:
  using: 'node20'
  main: 'index.js'
