name: 'GrabShot Screenshot'
description: 'Capture website screenshots in your CI/CD pipeline. Visual regression testing, OG image generation, documentation screenshots.'
author: 'GrabShot'
branding:
  icon: 'camera'
  color: 'blue'

inputs:
  url:
    description: 'URL to screenshot'
    required: true
  api-key:
    description: 'GrabShot API key (get free at grabshot.dev)'
    required: true
  output:
    description: 'Output file path'
    required: false
    default: 'screenshot.png'
  width:
    description: 'Viewport width'
    required: false
    default: '1280'
  height:
    description: 'Viewport height'
    required: false
    default: '800'
  full-page:
    description: 'Capture full page'
    required: false
    default: 'false'
  device:
    description: 'Device frame (iphone-15, pixel-8, macbook, none)'
    required: false
    default: 'none'
  format:
    description: 'Output format (png, jpeg, webp)'
    required: false
    default: 'png'
  block-ads:
    description: 'Block ads and trackers'
    required: false
    default: 'false'
  delay:
    description: 'Wait milliseconds before capture'
    required: false
    default: '0'

outputs:
  file:
    description: 'Path to the saved screenshot'
  size:
    description: 'File size in bytes'
  duration:
    description: 'Capture time in milliseconds'

runs:
  using: 'node20'
  main: 'dist/index.js'
