name: 'GrabShot Screenshot'
description: 'Capture website screenshots in your CI/CD pipeline. Device frames, full-page, PDF, and AI cleanup. Free tier: 25 screenshots/month.'
author: 'GrabShot <hello@grabshot.dev>'

branding:
  icon: 'camera'
  color: 'blue'

inputs:
  api-key:
    description: 'Your GrabShot API key (get one free at grabshot.dev)'
    required: true
  url:
    description: 'URL to capture'
    required: true
  output:
    description: 'Output file path'
    required: false
    default: 'screenshot.png'
  width:
    description: 'Viewport width (default: 1280)'
    required: false
    default: '1280'
  height:
    description: 'Viewport height (default: 800)'
    required: false
    default: '800'
  full-page:
    description: 'Capture full page (true/false)'
    required: false
    default: 'false'
  frame:
    description: 'Device frame: none, browser, iphone, macbook, ipad'
    required: false
    default: 'none'
  format:
    description: 'Output format: png, jpeg, webp, pdf'
    required: false
    default: 'png'
  delay:
    description: 'Wait time in ms before capture'
    required: false
    default: '0'
  ai-cleanup:
    description: 'AI cleanup to remove popups/banners (paid plans)'
    required: false
    default: 'false'

outputs:
  file:
    description: 'Path to the captured screenshot'
  size:
    description: 'File size in bytes'

runs:
  using: 'node20'
  main: 'dist/index.js'
